version: "3"

services:
  bot:
    build:
#      context: "."
      dockerfile: Dockerfile
    container_name: bot_ogi_creation
#    environment:
#      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
    restart: always